language: go

go:
  - 1.4.2

env:
  global:
    - TEST_PARSE_APPLICATION_ID=QjqWdPfnSauI2vGdAxOnYt1D8e4Dn4UPyXK4U4l5
    - TEST_PARSE_REST_API_KEY=VvKejQzEPp5RkRdnDEZtKZE54p0EFjqCQxjpHFWb
    - TEST_PARSE_MASTER_KEY=GoYB4Ouk7sDbkVHrYUUzrAvcUL3TCaQRzZvJACyv

before_install:
  - sudo pip install codecov

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/smartystreets/goconvey
  - go get github.com/smartystreets/assertions
  - go get ./...

script:
  - go test -v -coverprofile=coverage.txt -covermode=count

after_success:
  - codecov

