language: go

go:
  - 1.4.1

env:
  global:
    - TEST_PARSE_APPLICATION_ID=ABn7cwPXMCDU6eAy8wLIMRRwww73OGG7e8fQ3EKu
    - TEST_PARSE_REST_API_KEY=6eRwDWn5qnLEMd1V5xvDBxRq4QlXbBin78TSWpnK
    - TEST_PARSE_MASTER_KEY=Ytln0WFknVCcdvPRt3NXaXXUYwaONW4i1OBamrqQ

before_install:
  - sudo pip install codecov

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/smartystreets/goconvey
  - go get ./...

script:
  - echo $TEST_PARSE_MASTER_KEY
  - go test -v -coverprofile=coverage.txt -covermode=count

after_success:
  - codecov

